//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys.Services.Drv.TLM3.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sys.Services.Drv.TLM3.Culture.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad CRC value.
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine misfunction.
        /// </summary>
        internal static string Err_Machine {
            get {
                return ResourceManager.GetString("Err_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение настроек.
        /// </summary>
        internal static string Jrn_Change_Settings {
            get {
                return ResourceManager.GetString("Jrn_Change_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация времени.
        /// </summary>
        internal static string Jrn_Change_Time {
            get {
                return ResourceManager.GetString("Jrn_Change_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Появление фаз.
        /// </summary>
        internal static string Jrn_Phase_Appear {
            get {
                return ResourceManager.GetString("Jrn_Phase_Appear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропадание фаз.
        /// </summary>
        internal static string Jrn_Phase_Disappear {
            get {
                return ResourceManager.GetString("Jrn_Phase_Disappear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестное событие.
        /// </summary>
        internal static string Jrn_Unknown {
            get {
                return ResourceManager.GetString("Jrn_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read 30 min holes.
        /// </summary>
        internal static string Read30Min {
            get {
                return ResourceManager.GetString("Read30Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read day holes.
        /// </summary>
        internal static string ReadDay {
            get {
                return ResourceManager.GetString("ReadDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read holes is processing.
        /// </summary>
        internal static string ReadHoles {
            get {
                return ResourceManager.GetString("ReadHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read month/year holes.
        /// </summary>
        internal static string ReadMonth {
            get {
                return ResourceManager.GetString("ReadMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string Result_Empty {
            get {
                return ResourceManager.GetString("Result_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test request processing device issue date.
        /// </summary>
        internal static string Test_DateIssue {
            get {
                return ResourceManager.GetString("Test_DateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test datetime starting..
        /// </summary>
        internal static string Test_DT {
            get {
                return ResourceManager.GetString("Test_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test request processing network number.
        /// </summary>
        internal static string Test_NetNum {
            get {
                return ResourceManager.GetString("Test_NetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test request processing serial.
        /// </summary>
        internal static string Test_SN {
            get {
                return ResourceManager.GetString("Test_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test request processing soft version.
        /// </summary>
        internal static string Test_SV {
            get {
                return ResourceManager.GetString("Test_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test request processing device type.
        /// </summary>
        internal static string Test_Type {
            get {
                return ResourceManager.GetString("Test_Type", resourceCulture);
            }
        }
    }
}
